spring.application.name=campuseventmanager

server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5433/campuseventmanager
spring.datasource.username=postgres
spring.datasource.password=Tanmay@1234

spring.jpa.hibernate.ddl-auto=update